helpMenu:
  message: 'Civcraft is a unique Minecraft server where the players make the rules. It's an experiment for communities, political ideologies, debate and discussion. Most Minecraft servers have rules, like “no griefing”, “no stealing”, or “be nice”. Civcraft doesn't. However, that doesn't mean you can run wild throughout the world, pillaging and plundering all that you come across, because Civcraft isn't an ordinary vanilla Minecraft server. We have a collection of plugins that encourages co-operation between players by increasing Minecraft's base difficulty tenfold and puts players in control of justice.'
  plugins: 'NameLayer, Citadel, JukeAlert, RealisticBiomes, ItemExchange, CivChat2'

terms:
  kickDelay: 1200
  kickMessage: 'You must accept the terms using /sign in order to play.' 
  MovementRange: 15
  title:
    title: 'Welcome to Civcraft!'
    fadeIn: 20
    stay: 200
    fadeOut: 20
  subtitle: 'You need to agree to the TOS in chat'
  message: 'Civcraft is an experiment for communities, political ideologies, debate and discussion. Before you can start playing and join a civilization you must first read and agree to the terms of service'
  link: 'http://www.google.com'
  linkMessage: 'You can click this message to open up the terms of service.'
  confirm: 'Once you've read them, you can click this message to agree to the terms'
  
mysql:
  username: bukkit
  password: ''
  host: localhost
  port: 3306
  dbname: bukkit
  
donationNotifcation: false

unload_delay: 18000